#! /bin/bash

mkdir -p builds

if [ "$#" -gt 1 ] && [ $# -ne 0 ]; then
	echo "too many args just give the listing number $#"
	exit 1
fi

if  [ $# -eq 0 ]; then 
	for file in listing*.odin; do 
		buildname="builds/${file%.*}"
		echo "$file -> $buildname"
		odin build $file -file -debug -out:$buildname
	done
else
	re='^[0-9]+$'
	if ! [[ $1 =~ $re ]] ; then
		echo "error: Not a number" >&2; exit 1
	fi
	for file in listing*$1*.odin; do 
		buildname="builds/${file%.*}"
		echo "$file -> $buildname"
		odin build $file -file -debug -out:$buildname
	done
fi
